### PR TITLE
Add example a command(buttons navigations) with while and check

### PR DESCRIPTION
**Pull request by helish88**
- [x] New feature
- [ ] Fix bug
- [ ] Typo
- [ ] Other

## Checks
- [ ] Did you use the black formatter?
- [ ] Does this requires the users to change their code?
- [ ] Did you test?
- [ ] Have you updated the docs?
- [ ] Can you listen to our requests?
- [ ] Did you use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by kiki7000** [comment]
It would be better if you use `break` instead of `stop`

**Comment by helish88** [comment]
Agree. ill change

**Comment by kiki7000** [comment]
Could you divide the file?
I think it will crash because of `on_button_click`

**Comment by helish88** [comment]
image
code
```py
@bot.command()
async def buttons(ctx):
    """Buttons example of navigation with while and with check"""
    msg = await ctx.channel.send(embed=discord.Embed(color=discord.Color.random(), title="Navigation"),
                                 components=[
                                   [Button(style=ButtonStyle.blue, label="Backward", emoji="⏮️"),
                                    Button(style=ButtonStyle.red, label="Stop", emoji="❌"),
                                    Button(style=ButtonStyle.blue, label="Forward",  emoji="⏭️")]])
    def check(m):
        return m.user == ctx.author and m.message.channel == ctx.channel
    while True:
        try:
            res = await bot.wait_for("button_click", check=check, timeout=60)
        except asyncio.TimeoutError:
            await msg.delete()
            await ctx.send(embed=discord.Embed(color=discord.Color.red(),
                                                      title="Timeout"))
            break
        if res.channel == ctx.channel:
            if res.component.label == "Forward":
                await msg.edit(embed=discord.Embed(color=discord.Color.random(),
                                                   title="Forward"))
                await res.respond(
                    type=InteractionType.DeferredUpdateMessage
                )
            elif res.component.label == "Backward":
                await msg.edit(embed=discord.Embed(color=discord.Color.random(),
                                                   title="Backward"))
                await res.respond(
                    type=InteractionType.DeferredUpdateMessage
                )
            elif res.component.label == "Stop":
                await msg.edit(embed=discord.Embed(color=discord.Color.random(),
                                                   title="Stop"))
                await res.respond(
                    type=InteractionType.UpdateMessage
                )
                await msg.delete()```

**Comment by helish88** [comment]
and wdym `Could you divide the file?` this is one command

**Comment by kiki7000** [comment]
https://github.com/kiki7000/discord.py-components/pull/56#issuecomment-850964598

**Comment by kiki7000** [comment]
Why open two PRs

**Pull request closed without merging**
