### PR TITLE
Create simple.py

### PR DESCRIPTION
**Pull request by rachit1601**
## PR TYPE
Added example file. I'm planning to add more examples like calculator, etc
> Why did you open this PR (If it is other, please write a more detailed description.)
- [ ] New feature
- [ ] Fix bug
- [ ] Typo
- [x] Other

## Checks
- [ ] Did you use the black formatter?
- [ ] Does this requires the users to change their code?
- [x] Did you test?
- [ ] Have you updated the docs?
- [x] Can you listen to our requests?
- [ ] Did you use [conventional commits](https://www.conventionalcommits.org/ko/v1.0.0/)

### CODE REVIEW

**Comment by PythonSerious** [comment]
Hey, I went ahead and added some small touches to your file! @rachit1601 
```py
import discord
from discord.ext import commands
from discord_components import DiscordComponents, Button, ButtonStyle, InteractionType

bot = commands.Bot("!")

ddb = DiscordComponents(bot)


@bot.event
async def on_ready():
    print(f'Logged in as {bot.user}!')


@bot.command()
async def button(ctx):
    m = await ctx.send("Here is an example of a button",
            components=[[

                #Button(style=ButtonStyle.red, label="GREY", emoji="😂", disabled=True)
                Button(style=ButtonStyle.green, label="GREEN"), Button(style=ButtonStyle.red, label="RED"),
                Button(style=ButtonStyle.grey, label="GREY"), ],

                Button(style=ButtonStyle.blue, label="BLUE"),
                Button(style=ButtonStyle.URL, label="URL", url="https://www.example.com"), ])


@bot.event
async def on_button_click(m):
    """Possible interaction types:
        Pong
        ChannelMessageWithSource
        DeferredChannelMessageWithSource
        DeferredUpdateMessage
        UpdateMessage

    """
    await m.respond(

        type=InteractionType.ChannelMessageWithSource,
        content=f'{m.component.label} pressed'
    )


bot.run('TOKEN')


```

**Comment by kiki7000** [comment]
Could you put `ddb = DiscordComponents(bot)` this on the on_ready event?
And you can remove the `ddb = `

**Comment by PythonSerious** [comment]
> Could you put `ddb = DiscordComponents(bot)` this on the on_ready event?
> And you can remove the `ddb = `

@kiki7000 Im not sure how this would change anything at all?

**Comment by PythonSerious** [comment]
> Could you put `ddb = DiscordComponents(bot)` this on the on_ready event?
> And you can remove the `ddb = `



> Could you put `ddb = DiscordComponents(bot)` this on the on_ready event?
> And you can remove the `ddb = `


```py
import discord
from discord.ext import commands
from discord_components import DiscordComponents, Button, ButtonStyle, InteractionType

bot = commands.Bot("!")




@bot.event
async def on_ready():
    #DiscordComponents(bot)
    #^ uncomment this to init discord-components when the bot is ready.
    print(f'Logged in as {bot.user}!')


@bot.command()
async def button(ctx):
    m = await ctx.send("Here is an example of a button",
            components=[[
                Button(style=ButtonStyle.red, label="EMOJI", emoji="😂", disabled=True),
                Button(style=ButtonStyle.green, label="GREEN"), Button(style=ButtonStyle.red, label="RED"),
                Button(style=ButtonStyle.grey, label="GREY"), ],

                Button(style=ButtonStyle.blue, label="BLUE"),
                Button(style=ButtonStyle.URL, label="URL", url="https://www.example.com"),
             ])


@bot.event
async def on_button_click(m):
    DiscordComponents(bot)
    #^ Inits discordcomponents when the event is fired.
    """Possible interaction types:
        Pong
        ChannelMessageWithSource
        DeferredChannelMessageWithSource
        DeferredUpdateMessage
        UpdateMessage

    """
    await m.respond(

        type=InteractionType.ChannelMessageWithSource,
        content=f'{m.component.label} pressed'
    )


bot.run('TOKEN')



```

**Comment by kiki7000** [comment]
Without comment

**Comment by PythonSerious** [comment]
> Without comment

```py
import discord
from discord.ext import commands
from discord_components import DiscordComponents, Button, ButtonStyle, InteractionType

bot = commands.Bot("!")




@bot.event
async def on_ready():
    DiscordComponents(bot)
    print(f'Logged in as {bot.user}!')


@bot.command()
async def button(ctx):
    m = await ctx.send("Here is an example of a button",
            components=[[
                Button(style=ButtonStyle.red, label="EMOJI", emoji="😂", disabled=True),
                Button(style=ButtonStyle.green, label="GREEN"), Button(style=ButtonStyle.red, label="RED"),
                Button(style=ButtonStyle.grey, label="GREY"), ],

                Button(style=ButtonStyle.blue, label="BLUE"),
                Button(style=ButtonStyle.URL, label="URL", url="https://www.example.com"),
             ])


@bot.event
async def on_button_click(m):
    DiscordComponents(bot)
    #^ Inits discordcomponents when the event is fired.
    """Possible interaction types:
        Pong
        ChannelMessageWithSource
        DeferredChannelMessageWithSource
        DeferredUpdateMessage
        UpdateMessage

    """
    await m.respond(

        type=InteractionType.ChannelMessageWithSource,
        content=f'{m.component.label} pressed'
    )


bot.run('TOKEN')



```

**Comment by kiki7000** [comment]
you don't have to put `DiscordComponents(bot)` inside on_button_click
And it would be better if the Examples folder starts with lowercase like other folders

**Comment by PythonSerious** [comment]
> you don't have to put `DiscordComponents(bot)` inside on_button_click
> And it would be better if the Examples folder starts with lowercase like other folders

Well this isnt my pull, i was just editing some things but ill fix that in my pull request which you [can go see here](https://github.com/kiki7000/discord.py-components/pull/48)

Here is the modified simple.py:

```py
import discord
from discord.ext import commands
from discord_components import DiscordComponents, Button, ButtonStyle, InteractionType

bot = commands.Bot("!")




@bot.event
async def on_ready():
    DiscordComponents(bot)
    print(f'Logged in as {bot.user}!')


@bot.command()
async def button(ctx):
    m = await ctx.send("Here is an example of a button",
            components=[[
                Button(style=ButtonStyle.red, label="EMOJI", emoji="😂", disabled=True),
                Button(style=ButtonStyle.green, label="GREEN"), Button(style=ButtonStyle.red, label="RED"),
                Button(style=ButtonStyle.grey, label="GREY"), ],

                Button(style=ButtonStyle.blue, label="BLUE"),
                Button(style=ButtonStyle.URL, label="URL", url="https://www.example.com"),
             ])


@bot.event
async def on_button_click(m):
    """Possible interaction types:
        Pong
        ChannelMessageWithSource
        DeferredChannelMessageWithSource
        DeferredUpdateMessage
        UpdateMessage

    """
    await m.respond(

        type=InteractionType.ChannelMessageWithSource,
        content=f'{m.component.label} pressed'
    )


bot.run('TOKEN')```

**Pull request merged**
